### ISSUE TITLE
shadowsocks compatibility 

### ISSUE THREAD

**Issue by sinasalek** [clue/psocksd#25]
shadowsocks is a very sophisticated secure socks server. supporting it is advantages since it has a very good cross platform client and its protocol is encrypted unliked regular socks. yesss, android, windows, linux, mac, ios, etc
It alreasy has Python,C, C++, Go implementaion
https://shadowsocks.org

**Comment by clue** [comment]
Unfortunately, shadowsocks uses a non-standard, proprietary (although documented) protocol.

I'm very open to accepting PRs that add this, but I currently don't have any plans to add this myself anytime soon.

In case anybody wants to pick this up, make sure to let me know and I may be able to assist you :+1: 

FWIW, the SOCKS protocol has very good platform support, because multiple implementations exist for each platform. Also, I'm tempted to give (non-standard) encrypted SOCKS (SOCKS over TLS) a try, see https://github.com/clue/php-socks-react/issues/41 for eventual progress on this :+1:
